### PR TITLE
wrap server side protocol in cork/uncork

### PR DESCRIPTION
**Pull request by toolslive**

### CODE REVIEW

**Comment by domsj** [comment]
I thought we agreed on calling it just `flush`?

Also all those white space changes are kinda annoying (yes, even when one knows about adding ?w=1 to the url)

**Comment by toolslive** [comment]
- flush is confusing as we then have a flush operation on 2 levels (fd & channel).
- when you extract a function, the body will probably move to the left.

**Comment by domsj** [comment]
- I don't see the confusion. Actually imo the flush on channel level should trigger a flush on the (lower) fd level (but that may require changes to lwt which we don't want to wait for though...)
- indeed when you extract a function that could be the case, however here that is actually not the reason.
  Also there was actually no need to extract a function anyway: you could've added the call after the call to Lwt_io.flush a bit lower.
  Which is actually where it should be as flushing the fd before flushing the channel doesn't help.

**Comment by toolslive** [comment]
we need to manipulate the file descriptor BEFORE and AFTER the write. a "flush" is an operation that only makes sense AFTER a write.  Since you need to do something BEFORE and AFTER the write, you need to either extract a `_do_command` function or do it after every `->` of the match in the body.

Ok, you could have the something like this:

```
let flush connection =
  Lwt_unix.setsockopt connection.fd Lwt_unix.TCP_NODELAY true;
  Lwt_unix.setsockopt connection.fd Lwt_unix.TCP_NODELAY false;
  Lwt.return_unit

...
    _do_command conn backend command >>= fun death ->
    Server.flush conn >>= fun () ->
    Lwt.return death
```

but that's uglier than what's in the pull request.

**Comment by domsj** [comment]
Do we really need to manipulate the fd before and after each write? Maybe the proper solution here is to just set TCP_NODELAY to true all the time for the server protocol, as it uses Lwt_io.channels already anyway. That would be a 1 line change instead of 492 additions and 437 deletions, so definitely prettier.

Fwiw regarding extracting _do_command: you could already do sth before and after the write in `let rec loop ...`. The command was already extracted, you just separated to the read from the write phase, and the read phase is unaffected by the TCP_NODELAY flag anyway so that wasn't needed.

**Comment by domsj** [comment]
The 2012 Romain Slootmaekers set TCP_NODELAY to true for the inter node messaging: https://github.com/openvstorage/arakoon/commit/9c12cd6f3aa2e82372e883d9d41c071146e4e71a , so he seemed to agree.

I think the same should be done in client_helper.ml with_connection and in server.ml after the call to Lwt_unix.accept.
So that's actually each time the tcp keep alive settings are applied.
Fwiw I just noticed there's a bug in client_helper.ml with_connection: it does not apply tcp keepalive settings for the regular non-ssl case.

**Comment by toolslive** [comment]
The sockets in the inter node messaging are used in a weird way: either write-only or read-only. 
Setting TCP_NODELAY once in the server is simpler than wrapping the process response, and works for our channel based protocols. I'll do that.

**Pull request closed without merging**
