### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by delamonpansie**

### CODE REVIEW

**Comment by domsj** [comment]
Fyi: there's a lot more output on travis now, which I think will fail the build there (there's some limit on how much output a travis job is allowed to generate...)

**Comment by delamonpansie** [comment]
Why do you think there is a lot more output on travis?

**Comment by domsj** [comment]
previously the
```
+kill -0 26882
+echo -ne .
.+sleep 1
```
(which is repeated quite a few times)

wasn't there, it was only printing the dots.

Apparently the extra output isn't a problem for travis (yet) though (in the past we bumped into https://docs.travis-ci.com/user/common-build-problems/#Log-Length-exceeded )

**Review by domsj — APPROVED** [review]

**Comment by delamonpansie** [comment]
I fixed progress printing.

**Review by toolslive — APPROVED** [review]

**Pull request merged**
